=begin
  12. Highly divisible triangle number

  The sequence of triangle numbers is generated by adding the natural numbers.
  So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first
  ten terms would be:

      1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

  Let us list the factors of the first seven triangle numbers:

     1: 1
     3: 1,3
     6: 1,2,3,6
    10: 1,2,5,10
    15: 1,3,5,15
    21: 1,3,7,21
    28: 1,2,4,7,14,28

  We can see that 28 is the first triangle number to have over five divisors.

  What is the value of the first triangle number to have over five hundred
  divisors?
=end

def count_divisors(number)
  count = 0

  (1..number).each do |i|
    count += 1 if number % i == 0
  end

  return count
end

def highly_divisible_triangle_number(num_divisors)
  value = 0
  i = 1 # to increment value

  until count_divisors(value) > num_divisors
    value += i
    i += 1

    puts "- " + value.to_s + ": " + count_divisors(value).to_s
  end

  return value
end

=begin

puts count_divisors(3)
# => 2
puts count_divisors(6)
# => 4
puts count_divisors(28)
# => 5

=end

#puts highly_divisible_triangle_number(5)
# => 28
puts highly_divisible_triangle_number(500)
# => ?
